spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecomdb
    username: ecom
    password: secret
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

server:
  port: 8081